refactor docker install
Signed-off-by: zhihui wu <wu.zhihui1@zte.com.cn>

diff --git a/docker-install/install.d/30-docker-install b/docker-install/install.d/30-docker-install
--- a/docker-install/install.d/30-docker-install
+++ b/docker-install/install.d/30-docker-install
@@ -6,18 +6,47 @@ fi
 set -eu
 set -o pipefail
 
-yum install -y yum-utils device-mapper-persistent-data lvm2
-yum-config-manager \
-    --add-repo \
-    https://download.docker.com/linux/centos/docker-ce.repo
-yum makecache fast
+case $DISTRO_NAME in
+    centos7)
+        yum install -y yum-utils device-mapper-persistent-data lvm2
+        yum-config-manager \
+            --add-repo \
+            https://download.docker.com/linux/centos/docker-ce.repo
+        yum makecache fast
 
-if [ ${DIB_DOCKER_INSTALL_VERSION:-latest} == "latest" ]; then
-    yum install -y docker-ce
-else
-    yum install -y docker-ce-${DIB_DOCKER_INSTALL_VERSION}
-fi
+        if [ ${DIB_DOCKER_INSTALL_VERSION:-latest} == "latest" ]; then
+            yum install -y docker-ce
+        else
+            yum install -y docker-ce-${DIB_DOCKER_INSTALL_VERSION}
+        fi
+        ;;
+    ubuntu)
+        apt-get remove docker docker-engine docker.io
+        apt-get update
+        apt-get install -y \
+            apt-transport-https \
+            ca-certificates \
+            curl \
+            software-properties-common
+        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
+        add-apt-repository \
+           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
+           $(lsb_release -cs) \
+           stable"
+        apt-get update
+        if [ ${DIB_DOCKER_INSTALL_VERSION:-latest} == "latest" ]; then
+            apt-get install -y docker-ce
+        else
+            apt-get install -y docker-ce=${DIB_DOCKER_INSTALL_VERSION}
+        fi
+        ;;
+    *)
+        echo "invalid distro name!"
+        exit 1
+esac
+
 systemctl start docker
 systemctl status docker
 systemctl enable docker
 
+exit 0
